#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tsaleh/vim-align.git",
  "https://github.com/ervandew/supertab.git",
  "https://github.com/tomtom/tcomment_vim.git",
  "https://github.com/mitechie/pyflakes-pathogen.git",
  "https://github.com/sjl/gundo.vim.git",
  "https://github.com/fs111/pydoc.vim.git",
  "https://github.com/vim-scripts/pep8.git",
  "https://github.com/alfredodeza/pytest.vim.git",
  "https://github.com/reinh/vim-makegreen.git",
  "https://github.com/sontek/minibufexpl.vim.git",
  "https://github.com/vim-scripts/L9.git",
  "https://github.com/vim-scripts/TaskList.vim.git",
  "https://github.com/sontek/rope-vim.git",
  "https://github.com/mileszs/ack.vim.git",
  "https://github.com/sontek/minibufexpl.vim.git",
  "https://github.com/vim-scripts/FuzzyFinder.git",
  "https://github.com/tsaleh/vim-matchit.git",
  "https://github.com/Rip-Rip/clang_complete.git"
]

vim_org_scripts = [
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
